os: linux
dist: xenial

language: php

php:
  - 7.3

services:
  - docker

stages:
  - name: script
    if: branch in (master, development)

before_install:
  # Stop travis mysql as we're using MySQL in an image
  - sudo service mysql stop
  # log in to Docker to avoid toomanyrequest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Print Docker version for debugging purposes
  - docker --version
  # Prepare for deployment of Docker image
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 282251075226.dkr.ecr.eu-west-1.amazonaws.com #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  
     
# Run tests and push Docker image
script:
  # Run tests?
  
  # build and push linklives-transcribed-indexer image
  - docker build -f ./linklives-transcribed-indexer/Dockerfile_prod -t linklives-transcribed-indexer .
  - docker tag linklives-transcribed-indexer 282251075226.dkr.ecr.eu-west-1.amazonaws.com/linklives-transcribed-indexer:${IMAGE_TAG}
  - docker push 282251075226.dkr.ecr.eu-west-1.amazonaws.com/linklives-transcribed-indexer:${IMAGE_TAG}

  # build and push linklives-lifecourse-indexer image
  - docker build -f ./linklives-lifecourse-indexer/Dockerfile_prod -t linklives-lifecourse-indexer .
  - docker tag linklives-lifecourse-indexer 282251075226.dkr.ecr.eu-west-1.amazonaws.com/linklives-lifecourse-indexer:${IMAGE_TAG}
  - docker push 282251075226.dkr.ecr.eu-west-1.amazonaws.com/linklives-lifecourse-indexer:${IMAGE_TAG}